---
name: release cli multi architecture

"on":
  release:
    branches:
      - 'go'
    types: [released]

jobs:
  binary:
    strategy:
      matrix:
        arch: [arm, arm64, amd64, "386"]
        os: [linux, darwin, freebsd, windows]
        ldflags:
          - "-X digger/pkg/utils.version=${{ github.event.release.tag_name }}"
        exclude:
          - os: darwin
            arch: arm
          - os: darwin
            arch: "386"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build and publish binary artifact to GitHub
        id: build-and-release-binary
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          goversion: 1.21.1
          project_path: ./cli/cmd/digger
          binary_name: digger
          pre_command: export CGO_ENABLED=0
          ldflags: ${{ matrix.ldflags }}
          sha256sum: true
          md5sum: false
          asset_name: "digger-cli-${{matrix.os}}-${{matrix.arch}}"
          compress_assets: "OFF"
