name: Latest Release

on:
  release:
    types:
      - released

jobs:
  update_latest_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3    
      - name: Check if the release is marked as "latest"
        id: check_latest
        run: |
          if [ "${{ github.event.release.prerelease }}" == "false" ] && [ "${{ github.event.release.name }}" == "latest" ]; then
            echo "Latest release detected."
            echo "::set-output name=latest::true"
          else
            echo "Not the latest release or a pre-release."
            echo "::set-output name=latest::false"
          fi

      - name: Update latest tag
        if: steps.check_latest.outputs.latest == 'true'
        uses: EndBug/latest-tag@latest
        with:
          ref: latest
          description: Latest tag
          force-branch: false
